myproject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>/.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,
            {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('posts/', include('posts.urls')),
    path('projects/', include('projects.urls')),
    path('users/', include('users.urls')),





]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.posts_list, name="list"),
    path('new-post/', views.posts_new, name="new-post"),
    # catches anything below for the slug
    path('<slug:slug>', views.posts_page, name="page"),
]

projects/urls.py
from django.urls import path
from . import views


app_name = 'projects'


urlpatterns = [

    path('', views.projects_list, name='projects-lists'),
    path('new-project/', views.projects_form, name='projects-form')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),

]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Post(models.Model):

    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

projects/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Project(models.Model):

    company = models.CharField(max_length=75)
    projectname = models.CharField(max_length=75, null=True)
    jobtitle = models.CharField(max_length=75, default="", blank=True)
    description = models.TextField()
    skills = models.JSONField(default=list)
    startdate = models.DateField()
    enddate = models.DateField(null=True, blank=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.company

posts/forms.py
from django import forms
from . import models


class CreatePost(forms.ModelForm):

    class Meta:
        model = models.Post
        fields = ["title", "body", "slug", "banner"]

projects/forms.py
from django import forms
from . import models


class createProject(forms.ModelForm):

    class Meta:
        model = models.Project
        fields = ["projectname", "company", "jobtitle",
                  "description", "skills", "startdate", "enddate"]

myproject/views.py
# from django.http import HttpResponse
from django.shortcuts import render


def homepage(request):

    # return HttpResponse("Hello World")
    return render(request, 'home.html')


def about(request):
    # return HttpResponse("I am Ali I work at Mathnasium. I am a computer scientist")
    return render(request, 'about.html')

posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.


def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', {'posts': posts})


def posts_page(request, slug):

    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', {'post': post})


# checks to see if the user is login if not redirects to the login page
@login_required(login_url="/users/login/")
def posts_new(request):

    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            # save with user

            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.save()

            return redirect('posts:list')
    else:

        form = forms.CreatePost()
    return render(request, 'posts/post_new.html', {'form': form})

projects/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Project
from . import forms

# Create your views here.


def projects_list(request):

    projectItem = Project.objects.all().order_by('-startdate')
    return render(request, 'projects/projects_list.html', {'projects': projectItem})


@login_required(login_url="/users/login/")
def projects_form(request):

    if request.method == 'POST':
        form = forms.createProject(request.POST, request.FILES)
        if form.is_valid():

            newProject = form.save(commit=False)
            newProject.author = request.user
            newProject.save()

            return redirect('projects:projects-lists')
    else:
        form = forms.createProject()

    return render(request, 'projects/projects_form.html', {'form': form})

users/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.


def register(request):

    if request.method == "POST":
        form = UserCreationForm(request.POST)

        if form.is_valid():
            login(request, form.save())
            return redirect("posts:list")
    else:
        form = UserCreationForm()
    return render(request, 'users/register.html', {"form": form})


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # login here
            login(request, form.get_user())

            # after loging in if the next is shown or i click on new post and it brings me here after logging in
            # I should see the new post page
            if "next" in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("posts:list")

    else:

        form = AuthenticationForm()

    return render(request, 'users/login.html', {"form": form})


def logout_view(request):
    if request.method == "POST":

        logout(request)

        return redirect("posts:list")

posts/templates/posts/post_new.html
<!DOCTYPE html>
{% extends "layout.html" %}



{% block title %}
    New Post
{% endblock title %}

{% block content %}

    <section>
        <h1> New Post</h1>
        <form class="form-with-validation" action="{% url 'posts:new-post' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit" > Add Post</button>

        </form>
    </section>
{% endblock content %}

posts/templates/posts/post_page.html
<!DOCTYPE html>
{% extends "layout.html" %}



{% block title %}
    {{post.title}}
{% endblock title %}

{% block content %}
    <section> 
        <img 
            class="banner"
            src="{{post.banner.url}}" 
            alt="{{post.title}}"
        />
        <h1>{{post.title}}</h1>
        <p>{{post.body}}</p>
        <p>{{post.date}} by {{post.author}} </p>

       
    </section>
    
{% endblock content %}

posts/templates/posts/posts_list.html
<!DOCTYPE html>
{% extends "layout.html" %}



{% block title %}
    Posts
{% endblock title %}

{% block content %}
    <section> 
        <h1>Posts</h1>

        {%for post in posts%}
            <article class="post">
                <h2>
                    <a href= "{% url 'posts:page' slug=post.slug %}">
                        {{post.title}}
                    </a>
                </h2>
                <p>{{post.body}}</p>
                <p>{{post.slug}}</p>
                <p>{{post.date}} by {{post.author}} </p>
            </article>
            
        {% endfor %}
    </section>
    
{% endblock content %}

projects/templates/projects/projects_form.html
<!DOCTYPE html>
{% extends "layout.html" %}



{% block title %}
    Add Projects
{% endblock title %}

{% block content %}
    <section> 
        <h1>Add Project</h1>
        <form class="form-with-validation" action="{% url 'projects:projects-form' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit"> Add Project </button>
        </form>
    </section>
    
{% endblock content %}

projects/templates/projects/projects_list.html
<!DOCTYPE html>
{% extends "layout.html" %}



{% block title %}
    Projects
{% endblock title %}

{% block content %}
    <section> 
        <h1>Projects</h1>
        {%for project in projects%}

        <article class="project">
            <h2>
                {%if not project.projectname%}
                    {{project.company}}
                {% else%}
                    {{project.projectname}}
                {% endif%}
            </h2>
            <h3>{{project.jobtitle}}
            <p>{{project.startdate}} - {{project.enddate}}<p> 
            <br />
            <p>{{project.description}}</p>
            <br />
            <p> skills:
                {%for skill in project.skills%}
                    <span class="skill">{{skill}} </span>
                {% endfor %}
            </p>
        
            
        </article>

        {% endfor %}
    </section>


    
{% endblock content %}

templates/about.html
{% extends "layout.html" %}



{% block title %}
    About
{% endblock title %}

{% block content %}
    <h1>About</h1>
    <p>Check out my <a href="https://www.linkedin.com/in/ali-nablan/">Linkedin</a> page.</p>
{% endblock content %}

templates/home.html
{% extends "layout.html" %}



{% block title %}
    Home
{% endblock title %}

{% block content %}
    <h1>Home</h1>
    <p>Check out my <a href="/about">About</a> page.</p>
{% endblock content %}

templates/layout.html
<!DOCTYPE html>
 {% load static %} 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}

    </title>
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <script src="{% static 'js/main.js' %}" defer> </script>
</head>
<body>
    <nav>
        <a href="/">Home</a> |
        <a href="/about">About</a> |
        <a href="{% url 'posts:list' %}">Posts list</a> |
        {% if user.is_authenticated %}
            <a href="{% url 'posts:new-post' %}">New Post</a> |
            <a href="{% url 'projects:projects-lists' %}">Projects</a> |
            <a href="{% url 'projects:projects-form' %}"> Add Project </a> |
            <form class="logout" action ="{%url 'users:logout' %}" method="post">
                {% csrf_token %}
                <button class="logout-button" aria-label="User Logout" title="User Logout">Logout</button>
            </form>
            
        {% else %}
            <a href="{% url 'users:register' %}">Register</a> |
            <a href="{% url 'users:login' %}">Login</a> 
        {% endif %}
    </nav>
    <main>
        {% block content %}
        
        {% endblock  %}

    </main>
    
</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
{% extends "layout.html" %}



{% block title %}
    User Login
{% endblock title %}

{% block content %}
    <section> 
       <h1>User Login</h1>

       <form class="form-width-validation" action="{%url 'users:login' %}" method="post"> 
        {% csrf_token %}
        {{form}}

        {% if request.GET.next%}
            <input type="hidden" name = "next" value="{{request.GET.next}}" />

        {% endif %}
        <button class="form-submit">Submit</button>
       </form>

    </section>
    
{% endblock content %}

users/templates/users/register.html
<!DOCTYPE html>
{% extends "layout.html" %}



{% block title %}
    Register
{% endblock title %}

{% block content %}
    <section> 
       <h1>Register a New User</h1>

       <form class="form-width-validation" action="{% url 'users:register' %}" method="post"> 
        {% csrf_token %}
        {{form}}


        <button>Submit</button>
       </form>

    </section>
    
{% endblock content %}